name: Update Jupyter to Napptive Playground
on:
  push:
    branches:
      - 'main'
    paths:
      - "jupyter-template/napptive/component310/**"
      - "jupyter-template/napptive/componentPROD/**"
      - "jupyter-template/napptive/componentPVC/**"
jobs:
  deploy:
    name: Upload new version to the catalog
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - base: 'application-test'
            tag: '310'
          # - base: 'v3.9'
          #   tag: '39'
          # - base: 'v3.8'
          #   tag: '38'
          - base: 'latest'
            tag: 'PROD'
          - base: 'storage'
            tag: 'PVC'
    steps:
      - uses: actions/checkout@v3
      - uses: napptive-actions/catalog-push-action@v4.2.0
        env:
          PLAYGROUND_PAT: ${{ secrets.PLAYGROUND_PAT }}
        with:
          applicationPath: ./jupyter-template/napptive/component${{ matrix.tag }}/
          namespace: "davma-io"
          applicationName: "Jupyter"
          tag: "${{ matrix.base }}"